# Getting necessary features for file:
# top_cross_bu_dnc_stim_stage_detail

Here we will be isolating a couple features along with separating the data out by different rig company and eventually find the average of each feature per rig company

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

import datetime

from dateutil.relativedelta import relativedelta

from datetime import date
import numpy as np
import seaborn as sns
import os
import missingno as msno

## Load in the file

In [2]:
path = "Clean_Files"
os.makedirs(path, exist_ok = True)

save_path = path + "/"
# notice order of files
files = [
    "clean_top_cross_bu_dnc_stim_stage_detail.xlsx",
    "clean_bot_cross_bu_dnc_stim_stage_detail.xlsx",
    "clean_gcbu_dnc_recompletions.xlsx",
    "clean_gcbu_dnc_stim_stage.xlsx",
    "clean_monthly_production.xlsx"
]

In [3]:
df = pd.read_excel(save_path + files[0])
production = pd.read_excel(save_path + files[-1])

In [4]:
df

,#WELL_NAME,CURRENT_STATUS,UWI,UWI_SIDETRACK,JOB_CATEGORY,JOB_START_DATE,JOB_END_DATE,FINAL_JOB_STATUS,LIKE_KIND_GROUP,PRIMARY_JOB_TYPE,...,STIM_INT_TOP_DEPTH_TVD,L48DW_AREA,L48DW_DISTRICT,L48DW_REGION,PLANNED_FORMATION,TOTAL_PUMPS_ON_LOCATION,PUMPS_ONLINE_AT_STG_START,PUMPS_ONLINE_AT_STG_END,STIM_COMMENT,STIM_INT_COMMENT
0,WELL_NAME - 2019110026,Producing,2019110026,0,COMPLETIONS,08/17/2017 06:00:00,08/10/2018 19:46:00,COMPLETED,OCM - PP PUC,INITIAL COMPLETION,...,9377.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA UPPER,NaN,NaN,NaN,STAGE 1 FRAC OPERATIONSSTART TIME; 07:08 ...,STAGE 1 FRAC OPERATIONSSTART TIME; 07:08 ...
1,WELL_NAME - 2019110016,Producing,2019110016,0,COMPLETIONS,05/31/2017 07:00:00,08/15/2017 11:00:00,COMPLETED,OCM - PP PUC,INITIAL COMPLETION,...,6618.0,GOLDSMITH,PERMIAN CONVENTIONAL,PERMIAN,NaN,NaN,NaN,NaN,STAGE 1 FRAC OPSSTART TIME: 16:54 HRS F...,STAGE 1 FRAC OPSSTART TIME: 16:54 HRS F...
2,WELL_NAME - 2019110024,Producing,2019110024,0,COMPLETIONS,08/17/2017 06:00:00,08/15/2018 10:00:00,COMPLETED,OCM - PP PUC,INITIAL COMPLETION,...,9496.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,NaN,NaN,NaN,STAGE 1 FRAC OPERATIONSSTART TIME; 16:30 ...,STAGE 1 FRAC OPERATIONSSTART TIME; 16:30 ...
3,WELL_NAME - 2019110001,Producing,2019110001,0,COMPLETIONS,12/05/2017 10:00:00,01/03/2018 15:00:00,PRODUCING,NaN,RECOMPLETION,...,NaN,HOBBS,PERMIAN CONVENTIONAL,PERMIAN,NaN,NaN,NaN,NaN,STAGE 1 FRAC OPSSTART TIME: 11:58 HRS FI...,STAGE 1 FRAC OPSSTART TIME: 11:58 HRS FI...
4,WELL_NAME - 2019110031,Producing,2019110031,1,COMPLETIONS,01/25/2018 07:00:00,02/13/2019 04:59:00,PRODUCING,OCM - PP PUC,INITIAL COMPLETION,...,9591.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,NaN,NaN,NaN,STAGE 1 FRAC OPERATIONSSTART TIME; 2:24 ...,STAGE 1 FRAC OPERATIONSSTART TIME; 2:24 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2737,WELL_NAME - 2019110059,Completing,2019110059,0,COMPLETIONS,03/01/2019 09:00:00,NaN,COMPLETED,NaN,INITIAL COMPLETION,...,9597.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,22.0,21.0,21.0,NaN,NaN
2738,WELL_NAME - 2019110059,Completing,2019110059,0,COMPLETIONS,03/01/2019 09:00:00,NaN,COMPLETED,NaN,INITIAL COMPLETION,...,9599.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,22.0,21.0,21.0,NaN,NaN
2739,WELL_NAME - 2019110059,Completing,2019110059,0,COMPLETIONS,03/01/2019 09:00:00,NaN,COMPLETED,NaN,INITIAL COMPLETION,...,9595.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,22.0,21.0,21.0,NaN,NaN
2740,WELL_NAME - 2019110059,Completing,2019110059,0,COMPLETIONS,03/01/2019 09:00:00,NaN,COMPLETED,NaN,INITIAL COMPLETION,...,9606.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,22.0,21.0,20.0,NaN,NaN
2741,WELL_NAME - 2019110059,Completing,2019110059,0,COMPLETIONS,03/01/2019 09:00:00,NaN,COMPLETED,NaN,INITIAL COMPLETION,...,9614.0,AVALON,PERMIAN UNCONVENTIONAL,PERMIAN,WCA LOWER,22.0,21.0,21.0,NaN,NaN

In [5]:
df.columns

Index(['#WELL_NAME', 'CURRENT_STATUS', 'UWI', 'UWI_SIDETRACK', 'JOB_CATEGORY',
       'JOB_START_DATE', 'JOB_END_DATE', 'FINAL_JOB_STATUS', 'LIKE_KIND_GROUP',
       'PRIMARY_JOB_TYPE', 'JOB_PHASE_ACTUAL_START_DATE',
       'JOB_PHASE_ACTUAL_END_DATE', 'JOB_PHASE', 'JOB_OP_CODE', 'RIG_NAME',
       'RIG_ACCEPT_DATE', 'RIG_RELEASE_DATE', 'RIG_TYPE', 'RIG_CONTRACTOR',
       'DAILY_OPS_START_DATE_YEAR', 'DAILY_OPS_START_DATE',
       'DAILY_OPS_END_DATE', 'STIM_INT_START_DATE', 'STIM_INT_END_DATE',
       'STIM_INT_TREAT_TYPE', 'STIM_COMPANY', 'STIM_DIVERSION_COMPANY',
       'STIM_DIVERSION_METHOD', 'STIM_INT_DELIVERY_MODE',
       'STIM_INT_DIAGNOSTIC_METHOD', 'STIM_INT_FRAC_GRADIENT',
       'STIM_INT_BTM_HOLE_PRESS_METHOD', 'BREAKDOWN_PRESS',
       'STIM_INT_CLOSURE_PRESS_METHOD', 'STIM_INT_HYDROSTATIC_PRESS',
       'STIM_INT_TREAT_AVG_PRESS', 'STIM_INT_TREAT_MAX_PRESS',
       'STIM_INT_TREAT_MIN_PRESS', 'STIM_INT_PROPPANT_DESIGNED',
       'STIM_INT_PROPPANT_TOTAL', 'STIM_INT_PROPPANT_IN_WELLBORE',
       'STIM_INT_AVG_HYDRAULIC_POWER', 'STIM_INT_MAX_PUMP_POWER',
       'STIM_INT_MAX_PUMP_RATING', 'STIM_INT_TREAT_AVG_RATE',
       'STIM_INT_TREAT_MAX_RATE', 'STIM_INT_TREAT_MIN_RATE',
       'STIM_INT_POST_INST_SHUT_IN_PRESS', 'STIM_INT_INITIAL_SHUT_IN_PRESS',
       'STIM_INT_STIM_RESULT', 'STIM_INT_RESULT_DETAIL',
       'STIM_INT_STAGE_NUMBER', 'STIM_INT_STAGE_TYPE', 'STIM_START_DATE',
       'STIM_END_DATE', 'STIM_INT_TOP_DEPTH', 'STIM_INT_BTM_DEPTH',
       'ELEMENT_TOP_DEPTH', 'ELEMENT_BOTTOM_DEPTH', 'STIM_INT_BREAKDOWN_PRESS',
       'STIM_INT_AVG_RATE', 'STIM_INT_CLEAN_VOLUME_PUMPED',
       'STIM_INT_SLURRY_VOLUME_PUMPED', 'STIM_INT_VOLUME_RECOVERED',
       'STIMTREAT_ID', 'STIM_INT_BOTTOM_DEPTH_TVD', 'STIM_INT_TOP_DEPTH_TVD',
       'L48DW_AREA', 'L48DW_DISTRICT', 'L48DW_REGION', 'PLANNED_FORMATION',
       'TOTAL_PUMPS_ON_LOCATION', 'PUMPS_ONLINE_AT_STG_START',
       'PUMPS_ONLINE_AT_STG_END', 'STIM_COMMENT', 'STIM_INT_COMMENT'],
      dtype='object')

In [6]:
# here due to the fact that my file did not contian the commented out files
# I just went ahead and replaced them with their STIM_INT counter parts.
# That could be an error to do, but for now I'll stick with it.

wanted_features = [
    "UWI",
    "RIG_CONTRACTOR",
    "RIG_ACCEPT_DATE",
    "RIG_RELEASE_DATE",
    #"STG_START_DATE",           ## Missing
    #"STG_END_DATE",             ## Missing
    #"STG_SLURRY_VOLUME_PUMPED", ## Missing
    #"PROPPANT_DESIGNED",        ## Missing
    "STIM_INT_START_DATE",
    "STIM_INT_END_DATE",
    "STIM_INT_TOP_DEPTH",
    "STIM_INT_BTM_DEPTH",
    "STIM_INT_SLURRY_VOLUME_PUMPED",
    "STIM_INT_PROPPANT_DESIGNED",
]

In [7]:
# Remove those features that I wanted

working = df[wanted_features]

In [8]:
working

,UWI,RIG_CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STIM_INT_START_DATE,STIM_INT_END_DATE,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED
0,2019110026,CONTRACTOR - 2019110005,12/08/2017 06:00:00,01/04/2018 06:00:00,12/09/2017 07:08:00,12/09/2017 10:10:00,19305,19366,4029,110000.0
1,2019110016,CONTRACTOR - 2019110001,06/05/2017 06:00:00,06/14/2017 06:00:00,06/07/2017 16:54:00,06/07/2017 20:08:00,11428,11588,4776,150000.0
2,2019110024,CONTRACTOR - 2019110005,11/19/2017 06:00:00,12/08/2017 06:00:00,11/20/2017 16:30:00,11/20/2017 18:20:00,19326,19388,3842,110000.0
3,2019110001,CONTRACTOR - 2019110011,12/17/2017 10:00:00,12/18/2017 18:00:00,12/18/2017 11:10:00,12/18/2017 13:26:00,3912,4002,3145,200000.0
4,2019110031,CONTRACTOR - 2019110005,03/14/2018 06:00:00,04/07/2018 18:00:00,03/15/2018 02:24:00,03/15/2018 04:37:00,19580,19637,4074,110000.0
...,...,...,...,...,...,...,...,...,...,...
2737,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 00:51:00,09/15/2019 05:38:00,11168,11394,13618,660000.0
2738,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 08:51:00,09/15/2019 11:38:00,10929,11155,13723,660000.0
2739,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 14:23:00,09/15/2019 17:12:00,10690,10916,13820,660000.0
2740,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 22:24:00,09/16/2019 00:50:00,10452,10677,13070,660000.0
2741,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/16/2019 04:30:00,09/16/2019 06:55:00,10212,10438,12691,660000.0

In [9]:
# Here because I did not want to work with an entry that did not have a rig
# contractor id, I just dropped it.

working = working.dropna(subset = ["RIG_CONTRACTOR"])

In [10]:
working = working.reset_index(drop = True)
working

,UWI,RIG_CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STIM_INT_START_DATE,STIM_INT_END_DATE,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED
0,2019110026,CONTRACTOR - 2019110005,12/08/2017 06:00:00,01/04/2018 06:00:00,12/09/2017 07:08:00,12/09/2017 10:10:00,19305,19366,4029,110000.0
1,2019110016,CONTRACTOR - 2019110001,06/05/2017 06:00:00,06/14/2017 06:00:00,06/07/2017 16:54:00,06/07/2017 20:08:00,11428,11588,4776,150000.0
2,2019110024,CONTRACTOR - 2019110005,11/19/2017 06:00:00,12/08/2017 06:00:00,11/20/2017 16:30:00,11/20/2017 18:20:00,19326,19388,3842,110000.0
3,2019110001,CONTRACTOR - 2019110011,12/17/2017 10:00:00,12/18/2017 18:00:00,12/18/2017 11:10:00,12/18/2017 13:26:00,3912,4002,3145,200000.0
4,2019110031,CONTRACTOR - 2019110005,03/14/2018 06:00:00,04/07/2018 18:00:00,03/15/2018 02:24:00,03/15/2018 04:37:00,19580,19637,4074,110000.0
...,...,...,...,...,...,...,...,...,...,...
2734,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 00:51:00,09/15/2019 05:38:00,11168,11394,13618,660000.0
2735,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 08:51:00,09/15/2019 11:38:00,10929,11155,13723,660000.0
2736,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 14:23:00,09/15/2019 17:12:00,10690,10916,13820,660000.0
2737,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/15/2019 22:24:00,09/16/2019 00:50:00,10452,10677,13070,660000.0
2738,2019110059,CONTRACTOR - 2019110003,08/24/2019 06:00:00,09/17/2019 06:00:00,09/16/2019 04:30:00,09/16/2019 06:55:00,10212,10438,12691,660000.0

In [11]:
# Converting all dates so that they will be easier to work with later.

dates = [
    "STIM_INT_START_DATE",
    "STIM_INT_END_DATE",
    "RIG_ACCEPT_DATE",
    "RIG_RELEASE_DATE"
]

for d in dates:
    working[d] = pd.to_datetime(working[d], dayfirst=True)

In [12]:
# Getting rid of the "fluff" that is infront of the rig contractor id
# so I'm re working the row so that only the id is there

for i in range(0, len(working)):
    working.loc[i, "RIG_CONTRACTOR"] = working.loc[i, "RIG_CONTRACTOR"].split(" ")[2]

In [13]:
working

,UWI,RIG_CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STIM_INT_START_DATE,STIM_INT_END_DATE,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED
0,2019110026,2019110005,2017-08-12 06:00:00,2018-04-01 06:00:00,2017-09-12 07:08:00,2017-09-12 10:10:00,19305,19366,4029,110000.0
1,2019110016,2019110001,2017-05-06 06:00:00,2017-06-14 06:00:00,2017-07-06 16:54:00,2017-07-06 20:08:00,11428,11588,4776,150000.0
2,2019110024,2019110005,2017-11-19 06:00:00,2017-08-12 06:00:00,2017-11-20 16:30:00,2017-11-20 18:20:00,19326,19388,3842,110000.0
3,2019110001,2019110011,2017-12-17 10:00:00,2017-12-18 18:00:00,2017-12-18 11:10:00,2017-12-18 13:26:00,3912,4002,3145,200000.0
4,2019110031,2019110005,2018-03-14 06:00:00,2018-07-04 18:00:00,2018-03-15 02:24:00,2018-03-15 04:37:00,19580,19637,4074,110000.0
...,...,...,...,...,...,...,...,...,...,...
2734,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 00:51:00,2019-09-15 05:38:00,11168,11394,13618,660000.0
2735,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 08:51:00,2019-09-15 11:38:00,10929,11155,13723,660000.0
2736,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 14:23:00,2019-09-15 17:12:00,10690,10916,13820,660000.0
2737,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 22:24:00,2019-09-16 00:50:00,10452,10677,13070,660000.0
2738,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-16 04:30:00,2019-09-16 06:55:00,10212,10438,12691,660000.0

## Finding interpolated variables

In [14]:
inter_vars = [
    "Rig_Duration (days)",
    "Stim_Int_Duration (hrs)",
    "Stage_Length (meters)",
    "Production (monthly)",
]

In [15]:
# Here we are simultaniously finding the rig duration and the stim_int duration
# So the process is that, if one of the dates is invalid (i.e. just missing)
# just write it as -1.

# If both dates are valid, but the release/end date is before the start date
# then put -1.

# Else, put in the correct duration in either days or in hours.

for i in range(0, len(working)):
    start_rig = working.loc[i, "RIG_ACCEPT_DATE"]
    end_rig = working.loc[i, "RIG_RELEASE_DATE"]
    if(pd.isnull(start_rig) or pd.isnull(end_rig)):
        working.loc[i, inter_vars[0]] = -1
    else:
        temp = (end_rig - start_rig).components.days
        if(temp < 0):
            working.loc[i, inter_vars[0]] = -1
        else:
            working.loc[i, inter_vars[0]] = temp
    
    
    start_stim = working.loc[i, "STIM_INT_START_DATE"]
    end_stim = working.loc[i, "STIM_INT_END_DATE"]
    if(pd.isnull(start_stim) or pd.isnull(end_stim)):
        working.loc[i, inter_vars[1]] = -1
    else:
        temp = (end_stim - start_stim).components.hours + 24 * (end_stim - start_stim).components.days
        if(temp < 0):
            working.loc[i, inter_vars[1]] = -1
        else:
            working.loc[i, inter_vars[1]] = temp

In [16]:
working

,UWI,RIG_CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STIM_INT_START_DATE,STIM_INT_END_DATE,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED,Rig_Duration (days),Stim_Int_Duration (hrs)
0,2019110026,2019110005,2017-08-12 06:00:00,2018-04-01 06:00:00,2017-09-12 07:08:00,2017-09-12 10:10:00,19305,19366,4029,110000.0,232.0,3.0
1,2019110016,2019110001,2017-05-06 06:00:00,2017-06-14 06:00:00,2017-07-06 16:54:00,2017-07-06 20:08:00,11428,11588,4776,150000.0,39.0,3.0
2,2019110024,2019110005,2017-11-19 06:00:00,2017-08-12 06:00:00,2017-11-20 16:30:00,2017-11-20 18:20:00,19326,19388,3842,110000.0,-1.0,1.0
3,2019110001,2019110011,2017-12-17 10:00:00,2017-12-18 18:00:00,2017-12-18 11:10:00,2017-12-18 13:26:00,3912,4002,3145,200000.0,1.0,2.0
4,2019110031,2019110005,2018-03-14 06:00:00,2018-07-04 18:00:00,2018-03-15 02:24:00,2018-03-15 04:37:00,19580,19637,4074,110000.0,112.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2734,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 00:51:00,2019-09-15 05:38:00,11168,11394,13618,660000.0,24.0,4.0
2735,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 08:51:00,2019-09-15 11:38:00,10929,11155,13723,660000.0,24.0,2.0
2736,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 14:23:00,2019-09-15 17:12:00,10690,10916,13820,660000.0,24.0,2.0
2737,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 22:24:00,2019-09-16 00:50:00,10452,10677,13070,660000.0,24.0,2.0
2738,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-16 04:30:00,2019-09-16 06:55:00,10212,10438,12691,660000.0,24.0,2.0

In [17]:
# Next find stage lenght for each entry
working[inter_vars[2]] = working["STIM_INT_BTM_DEPTH"] - working["STIM_INT_TOP_DEPTH"]

In [18]:
working

,UWI,RIG_CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STIM_INT_START_DATE,STIM_INT_END_DATE,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED,Rig_Duration (days),Stim_Int_Duration (hrs),Stage_Length (meters)
0,2019110026,2019110005,2017-08-12 06:00:00,2018-04-01 06:00:00,2017-09-12 07:08:00,2017-09-12 10:10:00,19305,19366,4029,110000.0,232.0,3.0,61
1,2019110016,2019110001,2017-05-06 06:00:00,2017-06-14 06:00:00,2017-07-06 16:54:00,2017-07-06 20:08:00,11428,11588,4776,150000.0,39.0,3.0,160
2,2019110024,2019110005,2017-11-19 06:00:00,2017-08-12 06:00:00,2017-11-20 16:30:00,2017-11-20 18:20:00,19326,19388,3842,110000.0,-1.0,1.0,62
3,2019110001,2019110011,2017-12-17 10:00:00,2017-12-18 18:00:00,2017-12-18 11:10:00,2017-12-18 13:26:00,3912,4002,3145,200000.0,1.0,2.0,90
4,2019110031,2019110005,2018-03-14 06:00:00,2018-07-04 18:00:00,2018-03-15 02:24:00,2018-03-15 04:37:00,19580,19637,4074,110000.0,112.0,2.0,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 00:51:00,2019-09-15 05:38:00,11168,11394,13618,660000.0,24.0,4.0,226
2735,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 08:51:00,2019-09-15 11:38:00,10929,11155,13723,660000.0,24.0,2.0,226
2736,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 14:23:00,2019-09-15 17:12:00,10690,10916,13820,660000.0,24.0,2.0,226
2737,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 22:24:00,2019-09-16 00:50:00,10452,10677,13070,660000.0,24.0,2.0,225
2738,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-16 04:30:00,2019-09-16 06:55:00,10212,10438,12691,660000.0,24.0,2.0,226

## Production stuff

In [19]:
# the way this method works is that, given a start and an end date
# the function will return a list of tuples that represent all the months and years
# that a given well operated for. The end month is included in the list.

# Example, if start date was 1/1/20 and end date was 3/1/20, the list that will
# return is: [(1,2020), (2,2020), (3,2020)]

# If an invalid date is given then it will return an empty list.
# If an invalid date range (end comes before start) an empty list will be returned.

def all_dates(start, end):
    to_return = []
    
    if(pd.isnull(start) or pd.isnull(end)):
        return to_return
    
    start_year = start.year
    start_month = start.month
    
    end_year = end.year
    end_month = end.month
    
    if(end_year < start_year):
        return to_return
    elif(end_year == start_year and end_month < start_month):
        return to_return
    
    
    if(end_month+1 == 12):
        end_month = 1
        end_year += 1
    if(end_month+1 == 13):
        end_month = 2
        end_year += 1
        
    while(start_year != end_year or start_month != end_month):
        to_return.append((start_month, start_year))
        start_month += 1
        if(start_month == 13):
            start_month = 1
            start_year += 1
    
    return to_return

In [20]:
# This method will return the total oil production of a given well along
# a list of dates.

# if no production is found, then -1 will be put.
def find_production(uwi, dates):
    total_prod = 0
    
    for date in dates:
        m = date[0]
        y = date[1]
        
        temp = production[(production["UWI"] == uwi) & 
                          (production["CYCLE_YEAR"] == y) & 
                          (production["CYCLE_MONTH"]== m)]
        
        if(len(temp) == 0):
            total_prod += 0
        else:
            total_prod += temp.loc[0, "LEASE_OIL_PROD_VOL"]
    
    if(total_prod == 0):
        return -1
    else:
        return total_prod

In [21]:
# Doing all this process to get the correct production for each entry
for i in range(0, len(working)):
    strt = working.loc[i, "RIG_ACCEPT_DATE"]
    end = working.loc[i, "RIG_RELEASE_DATE"]
    w_id = working.loc[i, "UWI"]
    rig_dur = working.loc[i, "Rig_Duration (days)"]
    
    if(rig_dur != -1):
        d = all_dates(strt, end)
        prod = find_production(w_id, d)
        working["Oil Production (total)"] = prod
    else:
        working["Oil Production (total)"] = -1

In [22]:
working

,UWI,RIG_CONTRACTOR,RIG_ACCEPT_DATE,RIG_RELEASE_DATE,STIM_INT_START_DATE,STIM_INT_END_DATE,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED,Rig_Duration (days),Stim_Int_Duration (hrs),Stage_Length (meters),Oil Production (total)
0,2019110026,2019110005,2017-08-12 06:00:00,2018-04-01 06:00:00,2017-09-12 07:08:00,2017-09-12 10:10:00,19305,19366,4029,110000.0,232.0,3.0,61,-1
1,2019110016,2019110001,2017-05-06 06:00:00,2017-06-14 06:00:00,2017-07-06 16:54:00,2017-07-06 20:08:00,11428,11588,4776,150000.0,39.0,3.0,160,-1
2,2019110024,2019110005,2017-11-19 06:00:00,2017-08-12 06:00:00,2017-11-20 16:30:00,2017-11-20 18:20:00,19326,19388,3842,110000.0,-1.0,1.0,62,-1
3,2019110001,2019110011,2017-12-17 10:00:00,2017-12-18 18:00:00,2017-12-18 11:10:00,2017-12-18 13:26:00,3912,4002,3145,200000.0,1.0,2.0,90,-1
4,2019110031,2019110005,2018-03-14 06:00:00,2018-07-04 18:00:00,2018-03-15 02:24:00,2018-03-15 04:37:00,19580,19637,4074,110000.0,112.0,2.0,57,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 00:51:00,2019-09-15 05:38:00,11168,11394,13618,660000.0,24.0,4.0,226,-1
2735,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 08:51:00,2019-09-15 11:38:00,10929,11155,13723,660000.0,24.0,2.0,226,-1
2736,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 14:23:00,2019-09-15 17:12:00,10690,10916,13820,660000.0,24.0,2.0,226,-1
2737,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-15 22:24:00,2019-09-16 00:50:00,10452,10677,13070,660000.0,24.0,2.0,225,-1
2738,2019110059,2019110003,2019-08-24 06:00:00,2019-09-17 06:00:00,2019-09-16 04:30:00,2019-09-16 06:55:00,10212,10438,12691,660000.0,24.0,2.0,226,-1

In [23]:
# reduce the data frame to stuff we will use. So all the dates and the well
# ids are no longer needed.

final_features = [
    "RIG_CONTRACTOR",
    "STIM_INT_TOP_DEPTH",
    "STIM_INT_BTM_DEPTH",
    "STIM_INT_SLURRY_VOLUME_PUMPED",
    "STIM_INT_PROPPANT_DESIGNED",
    "Rig_Duration (days)",
    "Stim_Int_Duration (hrs)",
    "Stage_Length (meters)",
]

In [24]:
final_df = working[final_features]

In [25]:
final_df

,RIG_CONTRACTOR,STIM_INT_TOP_DEPTH,STIM_INT_BTM_DEPTH,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED,Rig_Duration (days),Stim_Int_Duration (hrs),Stage_Length (meters)
0,2019110005,19305,19366,4029,110000.0,232.0,3.0,61
1,2019110001,11428,11588,4776,150000.0,39.0,3.0,160
2,2019110005,19326,19388,3842,110000.0,-1.0,1.0,62
3,2019110011,3912,4002,3145,200000.0,1.0,2.0,90
4,2019110005,19580,19637,4074,110000.0,112.0,2.0,57
...,...,...,...,...,...,...,...,...
2734,2019110003,11168,11394,13618,660000.0,24.0,4.0,226
2735,2019110003,10929,11155,13723,660000.0,24.0,2.0,226
2736,2019110003,10690,10916,13820,660000.0,24.0,2.0,226
2737,2019110003,10452,10677,13070,660000.0,24.0,2.0,225
2738,2019110003,10212,10438,12691,660000.0,24.0,2.0,226

In [26]:
# This is just to find out how many unique rig contractors there are

unique_rigs = final_df["RIG_CONTRACTOR"].unique()
print(len(unique_rigs))
print(unique_rigs)

8
['2019110005' '2019110001' '2019110011' '2019110003' '2019000023'
 '2019110004' '2019000040' '2019000049']

In [27]:
statistics = pd.DataFrame(
    columns = final_df.columns.drop("RIG_CONTRACTOR").insert(0, "RIG_NUMBER").insert(1, "Stages Completed").drop("STIM_INT_TOP_DEPTH").drop("STIM_INT_BTM_DEPTH")
)
statistics

Empty DataFrame
Columns: [RIG_NUMBER, Stages Completed, STIM_INT_SLURRY_VOLUME_PUMPED, STIM_INT_PROPPANT_DESIGNED, Rig_Duration (days), Stim_Int_Duration (hrs), Stage_Length (meters)]
Index: []

In [28]:
all_rigs = []

for rig_id in unique_rigs:
    temp_rig = final_df[final_df["RIG_CONTRACTOR"] == rig_id].reset_index(drop = True)
    all_rigs.append(temp_rig)

In [29]:
for rig in range(0, len(all_rigs)):
    temp_row = {
        'RIG_NUMBER':                          "rig_%d" % (rig),
        'Stages Completed':                    len(all_rigs[rig]),
        'STIM_INT_SLURRY_VOLUME_PUMPED':       all_rigs[rig].describe().loc["mean", "STIM_INT_SLURRY_VOLUME_PUMPED"],
        'STIM_INT_PROPPANT_DESIGNED':          all_rigs[rig].describe().loc["mean", "STIM_INT_PROPPANT_DESIGNED"],
        'Rig_Duration (days)':                 all_rigs[rig].describe().loc["mean", "Rig_Duration (days)"],
        'Stim_Int_Duration (hrs)':             all_rigs[rig].describe().loc["mean", "Stim_Int_Duration (hrs)"],
        'Stage_Length (meters)':               all_rigs[rig].describe().loc["mean", "Stage_Length (meters)"],
    }
    statistics = statistics.append(temp_row, ignore_index = True)

In [30]:
statistics

,RIG_NUMBER,Stages Completed,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED,Rig_Duration (days),Stim_Int_Duration (hrs),Stage_Length (meters)
0,rig_0,1111,9811.912691,456919.140414,55.221422,28.497750,436.140414
1,rig_1,105,4799.980952,149675.480769,75.019048,28.076190,159.590476
2,rig_2,1,3145.000000,200000.000000,1.000000,2.000000,90.000000
3,rig_3,1404,11264.983618,533296.588151,77.769943,29.227920,199.934473
4,rig_4,87,5450.666667,192264.367816,67.275862,1.206897,186.896552
5,rig_5,28,5389.607143,176890.107143,-1.000000,0.857143,112.857143
6,rig_6,2,0.000000,179500.000000,242.000000,0.000000,112.000000
7,rig_7,1,4880.000000,110000.000000,-1.000000,2.000000,57.000000

In [31]:
statistics = statistics.set_index("RIG_NUMBER")
statistics

,Stages Completed,STIM_INT_SLURRY_VOLUME_PUMPED,STIM_INT_PROPPANT_DESIGNED,Rig_Duration (days),Stim_Int_Duration (hrs),Stage_Length (meters)
RIG_NUMBER,,,,,,
rig_0,1111,9811.912691,456919.140414,55.221422,28.497750,436.140414
rig_1,105,4799.980952,149675.480769,75.019048,28.076190,159.590476
rig_2,1,3145.000000,200000.000000,1.000000,2.000000,90.000000
rig_3,1404,11264.983618,533296.588151,77.769943,29.227920,199.934473
rig_4,87,5450.666667,192264.367816,67.275862,1.206897,186.896552
rig_5,28,5389.607143,176890.107143,-1.000000,0.857143,112.857143
rig_6,2,0.000000,179500.000000,242.000000,0.000000,112.000000
rig_7,1,4880.000000,110000.000000,-1.000000,2.000000,57.000000

## Final determination of "Best"

In [ ]:
# to be filled later